- name: install prerequisite for Debian/Ubuntu ruby-install (build mode)
  apt: pkg={{item}} state=present
  with_items:
    - build-essential 
    - bison
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libffi-dev
  when: ruby_install_mode == "build"