
- name: set fact for ruby version install
  set_fact:
    ruby_version_name: ruby-{{ install_version }}
    ruby_archive_name: ruby-{{ install_version }}-{{ ansible_os_family|lower }}-{{ ansible_architecture }}.tar.gz
    ruby_install_path: "{{ ruby_prefix }}/bin/ruby"

- name: check if ruby is already installed
  stat: path="{{ ruby_install_path }}"
  register: ruby_version_installed

- name: install ruby {{ install_version }} from upstream
  command: /usr/local/bin/ruby-install ruby {{ install_version }} -- --disable-install-rdoc --enable-load-relative --prefix={{ ruby_prefix }}
  when: (ruby_version_installed.stat.exists == False)

- name: check if ruby is already installed # retry
  stat: path="{{ ruby_install_path }}"
  register: ruby_version_installed

- name: archive {{ install_version }} version
  archive:
    path: "{{ ruby_prefix }}"
    dest: /var/tmp/ruby-{{ install_version }}-{{ ansible_os_family|lower }}-{{ ansible_architecture }}.tar.gz
  register: archive_created
  when: (ruby_version_installed.stat.exists == True)

- name: check if ruby binary is available on remote system
  stat: path="/var/tmp/{{ ruby_archive_name }}"
  register: ruby_archive_remote

- name: copy archive from remote to local
  fetch:
    src: /var/tmp/{{ ruby_archive_name }}
    dest: "{{ binary_path }}/{{ ruby_archive_name }}"
    flat: yes
  when: (ruby_archive_remote.stat.exists == True)
