
- name: set fact for ruby version install
  set_fact:
    ruby_version_name: ruby-{{ install_version }}
    ruby_archive_name: ruby-{{ install_version }}-{{ ansible_os_family|lower }}-{{ ansible_distribution_version }}-{{ ansible_architecture }}.tar.gz
    ruby_bin_path: "{{ ruby_prefix }}/{{ install_version }}/bin/"
    ruby_install_path: "{{ ruby_prefix }}/{{ install_version }}/bin/ruby"

- name: check if ruby is already installed
  stat: path="{{ ruby_install_path }}"
  register: ruby_version_installed

- name: install ruby {{ install_version }} from upstream
  command: /usr/local/bin/ruby-install {{ ruby_install_url_arg }} -- --disable-install-rdoc --enable-load-relative --prefix={{ ruby_prefix }}/{{ install_version }}
  when: (ruby_version_installed.stat.exists == False)
  become: yes

- name: check if ruby is already installed # retry
  stat: path="{{ ruby_install_path }}"
  register: ruby_version_installed

- name: check if ruby archive existed
  stat: path="/var/tmp/{{ ruby_archive_name }}"
  register: ruby_archive_existed

- name: archive {{ install_version }} version
  archive:
    path: "{{ ruby_prefix }}/{{ install_version }}"
    dest: /var/tmp/{{ ruby_archive_name }}
  register: archive_created
  when: (ruby_version_installed.stat.exists == True) and (ruby_archive_existed.stat.exists == False)

- name: check if ruby binary is available on remote system
  stat: path="/var/tmp/{{ ruby_archive_name }}"
  register: ruby_archive_remote

- name: check if ruby binary is available on local system
  local_action: stat path={{ binary_path }}/{{ ruby_archive_name }}
  register: ruby_archive_local
  become: no

- name: copy archive from remote to local
  fetch:
    src: /var/tmp/{{ ruby_archive_name }}
    dest: "{{ binary_path }}/{{ ruby_archive_name }}"
    flat: yes
  when: ruby_archive_remote.stat.exists and not ruby_archive_local.stat.exists

- include: "ruby_gem_install.yml"
